services: 
  db:
    build:
      context: ./Back
      dockerfile: Dockerfile-postgres
    container_name: syncadia_db
    environment:
      POSTGRES_DB: syncadia_db
      POSTGRES_USER: Syncadia_User
      POSTGRES_PASSWORD: Syncadia2026
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Back/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: syncadia_back
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/syncadia_db
      SPRING_DATASOURCE_USERNAME: Syncadia_User
      SPRING_DATASOURCE_PASSWORD: Syncadia2026
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: syncadia_front
    depends_on:
      - backend
      - db
    ports:
      - "8081:80"
    environment:
      - VITE_API_URL=http://backend:8080
volumes:
  db_data: