services: 
  db:
    image: mysql
    container_name: syncadia_db
    environment:
      MYSQL_ROOT_PASSWORD: Syncadia2026
      MYSQL_DATABASE: syncadia_db
      MYSQL_USER: syncadia
      MYSQL_PASSWORD: Syncadia2026
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d

  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: syncadia_back
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/syncadia_db
      SPRING_DATASOURCE_USERNAME: syncadia
      SPRING_DATASOURCE_PASSWORD: Syncadia2026
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: syncadia_front
    depends_on:
      - backend
      - db
    ports:
      - "8081:80"
    environment:
      - VITE_API_URL=http://backend:8080
volumes:
  db_data: